name: Build Dev

on:
  push:
    branches: [ develop ]

jobs:
  deploy-rancher:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 7
          format: 'YYYYMMDDHHmmss'

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Image
        run: |-
          docker build --no-cache \
          -f dockerfiles/dev/Dockerfile \
          -t asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:dev.${{ steps.time.outputs.time }} \
          -t asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:dev.latest .

      - run: |
          gcloud auth configure-docker -q

      - name: Build
        run: |
          docker push asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:dev.${{ steps.time.outputs.time }}
          docker push asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:dev.latest

      - name: Rancher Deploy
        uses: sekassel-research/actions-rancher-update@1.1.3
        with:
          rancher_url: http://rancher-dev.5p-studio.com:8080
          rancher_access: ${{ secrets.DEV_RANCHER_ACCESS_KEY }}
          rancher_key: ${{ secrets.DEV_RANCHER_SECRET_KEY }}
          project_id: 1a5
          stack_name: ABDRINK
          service_name: ABDRINK-Website
          docker_image: asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:dev.latest
